name: Deploy to Ubuntu Server

on:
  push:
    branches: ["develop"]  
  pull_request:
    branches: ["develop"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: whoami